spring:
  application:
    name: okto-configuration-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Calin606/microservices-config-server
          username: Calin606
          password: Student226728
          clone-on-start: true

server:
  port: 8888