spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shopmedb
    username: udemy
    password: teaching12
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database: POSTGRESQL
    generate-ddl: true
  application:
    name: okto-order-service

server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}